# thanks to https://github.com/travis-ci/travis-ci-php-example
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  - 5.5
  - 5.6
  - 7.0

# whitelist which branches to run on
branches:
  only:
    - master


# execute any number of scripts before the test run, custom env's are available as variables
before_script:
 - composer self-update
 - composer install
 - mkdir -p tests/_log
 - mkdir -p content/drafts content/pages
 - php -S localhost:8000 -t web/ > /dev/null 2>&1 &
 - sudo chmod -R 777 content
 - ./bin/codecept build

script: ./bin/codecept run # run codeception tests!

# configure notifications (email, IRC, campfire etc)
notifications:
  email:
    - mail@stephcook.co.uk
    - mail@qasashraf.co.uk
